- name: install mariadb server package (RedHat)
  tags: RedHat,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "RedHat"
 
- name: install mariadb server
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
